[package]
name = "nananiji-tg-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "1.6"
urlencoding = "2.1"
json = "0.12"
chrono = "0.4"
chrono-tz = "0.6"
