[package]
name = "twitter-telegram-forwarder"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "1.7"
urlencoding = "2.1"
json = "0.12"
chrono = "0.4"
chrono-tz = "0.8"
